### ISSUE TITLE
No way to close information pane on mobile view

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#383]
When in mobile view, the "X" tab that dismisses the information pane (for About, Lot, and other views) is not visible, so there's no way to close it.  

We should modify the CSS so that the X appears in the content pane instead of as a tab.

**Comment by andycochran** [comment]
This was done by design. There are some issues that arise from letting the user to close the info panel. 

First, closing the info panel would not give the user access to any other content or tools. All it would do is hide content. Functionally, there's no reason to close the info panel aside from the possibility of giving the map more real estate. 

However, the map is currently an explicit height on small screens. This doesn't have to be the case. When on the index route, we can map the map taller by… 

Add this to `routes/application.js` (I'm not sure if this is cool; @allthesignals ): 

```js
Ember.Route.reopen({
  activate: function() {
    let cssClass = this.toCssClass();
    if (cssClass !== 'application') {
      Ember.$('body').addClass(cssClass);
    }
  },
  deactivate: function() {
    Ember.$('body').removeClass(this.toCssClass());
  },
  toCssClass: function() {
    return this.routeName.replace(/\./g, '-').dasherize();
  }
});
```

And add this to `l-default.scss`: 

```scss
body.index {
  @include breakpoint(small only) {
    .map-grid,
    .map-container {
      height: calc(100vh - 14rem);
    }
  }

  @include breakpoint(medium) {
    .map-grid {
      height: 100vh;
    }
  }
}
```

BUT (big but), this presents us with the same issue that plagued opening/closing the info panel on large screens. The map doesn't resize when its parent container resizes. The map requires a resize event. 

I'll push up my branch with this so you can see…
