### ISSUE TITLE
Two Xs

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#494]
On IE, there are two Xs while typing in the search input. 

![image](https://user-images.githubusercontent.com/409279/35814633-91cbe06e-0a64-11e8-92f0-d99e88d02c50.png)

Since we're adding our own clear button, we should add the following CSS to hide IE's default one: 

```css
::-ms-clear {
  display: none;
}
```
